version: "3.7"
services:
  web:
    image: dogalert/dogalert-web:release-1.0
    volumes:
      - /data/dogalert/www:/var/www/dogalert
      - /data/dogalert/ssl:/etc/nginx/ssl
    ports:
      - mode: host
        target: 443
        published: 443
        protocol: tcp
      - mode: host
        target: 80
        published: 80
        protocol: tcp
    env_file:
      - .env
  php:
    image: dogalert/dogalert-php:release-1.0
    volumes:
      - /data/dogalert/www:/var/www/dogalert
      - /data/log/dogalert.log:/usr/src/dogalert/storage/logs/laravel.log
    env_file:
      - .env
  redis:
    image: redis
